# -*- coding: utf-8 -*-
"""LML_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1-XvYfGYDrkm__dF7CaCBkwkLBe6GzF

# **Loading Data**
"""

# Loading a Sample Dataset

# Load scikit-learn's datasets
from sklearn import datasets

# Load digits dataset
digits = datasets.load_digits()

# Create features matrix
features = digits.data

# Create target vector
target = digits.target

# View first observation
features[0]

# Creating a Simulated Dataset

# Load library
from sklearn.datasets import make_regression

#Generate features matrix, target vector, and the true coefficients
features, target, coefficients = make_regression(n_samples = 100,
                                                 n_features = 3,
                                                 n_informative = 3,
                                                 n_targets = 1,
                                                 noise = 0.0,
                                                 coef = True,
                                                 random_state = 1)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

# Load library
from sklearn.datasets import make_classification

# Generate features matrix and target vector
features, target = make_classification(n_samples = 100,
                                       n_features = 3,
                                       n_informative = 3,
                                       n_redundant = 0,
                                       n_classes = 2,
                                       weights = [.25, .75],
                                       random_state = 1)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

# Load library
from sklearn.datasets import make_blobs

# Generate feature matrix and target vector
features, target = make_blobs(n_samples = 100,
                                       n_features = 2,
                                       centers = 3,
                                       cluster_std = 0.5,
                                       shuffle = True,
                                       random_state = 1)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

# Load library
import matplotlib.pyplot as plt

# View scatterplot
plt.scatter(features[:,0], features[:,1], c=target)
plt.show()

# Loading a CSV File

# Load library
import pandas as pd

# Create URL
path = '/content/industry.csv'
# Load dataset
dataframe = pd.read_csv(path)

# View first two rows
dataframe.head(2)

# Loading an Excel File

# Load library
import pandas as pd

# Create URL
path = '/content/country.xlsx'

# Load data
dataframe = pd.read_excel(path, header=1)

# View the first two rows
dataframe.head(2)

import pandas as pd
import json

# Create URL
path = '/content/dwsample1-json.json'

# Load data
with open(path) as file:
    data = json.load(file)

# Convert JSON object to DataFrame
dataframe = pd.DataFrame([data])

# View the first two rows
print(dataframe.head(2))

# Querying a SQL Database

# Load libraries
import pandas as pd
from sqlalchemy import create_engine

# Create a connection to the database
database_connection = create_engine('sqlite:///sample.db')

# Load data
dataframe = pd.read_sql_query('SELECT * FROM data', database_connection)

# View first two rows
dataframe.head(2)